TRAIN:
  DATASET: imagenet1k
  SUBSET_FILE_PATH: "./data/imagenet_subsets/semi_1percent.txt"
  BATCH_SIZE: 128
  FILE_NAME: ""
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_FILE_PATH: ""
VAL:
  DATASET: imagenet1k
  BATCH_SIZE: 128
  FILE_NAME: ""
DATA:
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PATH_TO_DATA_DIR: "./datasets/imagenet1k/"
MODEL:
  BACKBONE_ARCH: resnet18
  BACKBONE_WIDTH_MULT: 1.0
  PRE_TRAINED_SUP: False
  PRE_TRAINED_PATH: ""
SOLVER:
  OPTIMIZING_METHOD: SGD
  NESTEROV: True
  LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_END: 0.0
  TOTAL_EPOCHS: 60
  WARMUP_EPOCHS: 0
  BASE_LR: 0.03
  MIN_LR: 1.0e-6
  MOMENTUM: 0.9
  CLIP_GRAD: 0.0
  SCHEDULER: 'cos'
  MILESTONES: [36, 48]
LOG_STEP: 10
# stage from [TRAIN, VAL, TEST, FT]
SSL_METHOD: DINO
EVAL_METHOD: Semi
STAGE: TRAIN 
DISTRIBUTED: False
SEED: 0
DIST_BACKEND: 'nccl'
N_NODES: 1
WORLD_SIZE: 1
NODE_RANK: 0
DIST_URL: "env://"
WORKERS: 16
OUTPUT_DIR: ./logs/DINO_R18_SEMI