TRAIN:
  BATCH_SIZE: 128
  CHECKPOINT_PERIOD: 20
MULTI_VIEWS_TRANSFORMS:
  GLOBAL_CROPS_SCALE: [0.3, 1.0]
  LOCAL_CROPS_SCALE: [0.05, 0.3]
  LOCAL_CROPS_NUMBER: 6  
  RANDOM_HORIZONTAL_FLIP_PROB: [0.5, 0.5]
  GAUSSIAN_BLUR_PROB: [1.0, 0.1, 0.5] # global_1, global_2, local
  COLOR_JITTER_PROB: [0.8, 0.8]
  COLOR_JITTER_INTENSITY: [0.4, 0.4, 0.2, 0.1]
  GREYSCALE_PROB: [0.2, 0.2]
  CROP_PROB: [1.0, 1.0]
  LOCAL_CROP_SIZE: 128
  GLOBAL_CROP_SIZE: 224
  SOLARIZATION_PROB: [0.0, 0.2]
  CROPS_FOR_ASSIGN: [0, 1]
  NMB_CROPS: [2, 6]
  LAMBDAS: [0.4, 0.6]
MODEL:
  BACKBONE_ARCH: mobilenet_v2
  MODEL_MOMENTUM: 0.996
DINOHead:
  OUTPUT_DIM: 4096
  USE_BN_IN_HEAD: True
DINO:
  WARMUP_TEACHER_TEMP_EPOCHS: 0
SOLVER:
  OPTIMIZING_METHOD: LARS
  WEIGHT_DECAY: 1.0e-6
  WEIGHT_DECAY_END: 1.0e-6
  TOTAL_EPOCHS: 40
  BASE_LR: 0.48
  MIN_LR: 0.0048
  FREEZE_LAST_LAYER: 1
LOG_STEP: 20
# stage from [TRAIN, VAL, TEST, FT]
SSL_METHOD: DINO
STAGE: TRAIN 
DISTRIBUTED: False
SEED: 0
DIST_BACKEND: 'nccl'
N_NODES: 1
WORLD_SIZE: 1
NODE_RANK: 0
DIST_URL: "env://"
WORKERS: 16
USE_FP16: False